services:  
  py-mysql:
    build: . 
    ports:
      - "5000:5000"
    depends_on:
      - mysql 
    networks: 
      - api-network  

  mysql:
    image: mysql:5.7 
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: inventory
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    ports:
      - "3306:3306" 
    networks: 
      - api-network  

networks: 
  api-network: 
    driver: bridge 
